---
title: "Data import"
output: github_document
---
```{r, echo=F}
library(tidyverse)
library(readxl)
library(haven)
```



## Data Import: CSVs

Let's import data using the `readr` package.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names((litters_df))
```

Look at the data

```{r}
litters_df
head(litters_df) #first 6 rows
tail (litters_df) # last 6 rows
```

```{r, eval=F}
view(litters_df) #usually not in Rmd files as view opens a new window
```

```{r}
skimr::skim(litters_df)
```

`read_csv` options

```{r, eval=F}
read_csv("data/FAS_litters.csv", na = c("", "NA", 999, 88), skip = 2) 
#define NAs, how many rows you want to skip
```

## Other file formats

We need to read in an excel spreadsheet

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r, eval = F}
view(mlb_df)
```

```{r}
lotr_words_df = read_excel(
  "data/LotR_words.xlsx",
  range = "B3:D6"
)
```

## Still more file formats

Read in a SAS dataset

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


## Data export

```{r}
write.csv(lotr_words_df, file = "data/lotr_words_df.csv")
```



## Why not base r??

```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
# it automatically formats things that you might want as something else, tedious 
```



















